"""结果空间域 · 指标评估管理业务对象 (business objects)."""
from .evaluation import (
    CalcType,
    EvaluateObject,
    EvaluateSnapshot,
    EvaluateTask,
    EvaluateTemplate,
    ObjectStatus,
    ObjectTypeDict,
    SceneType,
    ScoreRule,
    TaskIndicatorRecord,
    TaskStatus,
    TemplateIndicatorRel,
    TemplateStatus,
    new_object,
    new_task,
    new_template,
)

__all__ = [
    "ObjectStatus",
    "TemplateStatus",
    "SceneType",
    "CalcType",
    "TaskStatus",
    "ObjectTypeDict",
    "EvaluateObject",
    "EvaluateTemplate",
    "TemplateIndicatorRel",
    "ScoreRule",
    "EvaluateTask",
    "TaskIndicatorRecord",
    "EvaluateSnapshot",
    "new_object",
    "new_template",
    "new_task",
]
